version: '3.1'

services:
  springboot:
    build: .
    image: dockerhandson/springboot-mongo:latest
    container_name: springboot
    ports:
      - 8182:8080
    environment:
      DB_URI: mongodb://mongo:27017
      DB_NAME: test
    depends_on:
      - mongo
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure   

  mongo:
    image: mongo
    container_name: springboot-mongo
    volumes:
      - data:/data/db
      - data-bkp:/data/bkp
    
volumes:
  data:
  data-bkp:
